---
title: "データ分析1"
author: "Kyohei ITO"
date: "12/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


パッケージの読み込み

```{r}

library(tidyverse)
library(psych)
library(GPArotation)
library(lavaan)
library(semTools)
library(semPlot)

```

データの読み込み

```{r}
guess_encoding("/home/rstudio/fanaticism/data/haiyu.csv")

Data_m =  read_csv("/home/rstudio/fanaticism/data/musician.csv", locale = locale(encoding = "CP932"))
Data_s =  read_csv("/home/rstudio/fanaticism/data/sport.csv", locale = locale(encoding = "CP932"))
Data_h =  read_csv("/home/rstudio/fanaticism/data/haiyu.csv", locale = locale(encoding = "CP932"))
Data_i =  read_csv("/home/rstudio/fanaticism/data/idle.csv",locale = locale(encoding = "CP932"))
Data_o =  read_csv("/home/rstudio/fanaticism/data/owarai.csv",locale = locale(encoding = "CP932"))

#group列の追加

Data_m = mutate(Data_m, group = 1)
Data_s = mutate(Data_m, group = 2)
Data_h = mutate(Data_h, group = 3)
Data_i = mutate(Data_i, group = 4)
Data_o = mutate(Data_m, group = 5)

#DataFrameの結合

Data = rbind(Data_m, Data_s, Data_h, Data_i, Data_o)

#ダミー項目の削除

Data = select(Data, -"Q.13-m3")


#逆転項目の修正

Data = mutate(Data, `Q.5-m8` = (8-`Q.5-m8`),
                `Q.8-m6` = (8-`Q.8-m6`),
                `Q.9-m10` = (8-`Q.9-m10`),
                `Q.16-m3` = (8-`Q.16-m3`),
                `Q.17-m1` = (8-`Q.17-m1`))

#不必要な項目の削除

Data = select(Data, -(131:142))



```

相関係数行列
```{r}

corD = Data %>% select(-(1:14)) %>% cor()
write.csv(corD, "cor.csv")

```


探索的因子分析

ファン心理

平行分析
```{r}
Data %>% select((15:87)) %>% 
  fa.parallel()

```

ガットマン基準
```{r}
corx = cor(select(Data,(15:87)))
eigen(corx)$values

```

```{r}

fa.result = fa(select(Data,(15:87)),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result$loadings, "fa11.csv")
#print(fa.result$loadings, digits = 3, sort=TRUE,cutoff=0)

```
```{r}
fa.result1 = fa(select(Data,(15:87),-`Q.5-m8`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result1$loadings, "fa12.csv")
```

```{r}
fa.result2 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result2$loadings, "fa13.csv")
```

```{r}
fa.result3 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result3$loadings, "fa14.csv")
```

```{r}
fa.result4 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result4$loadings, "fa15.csv")
```

```{r}
fa.result5 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result5$loadings, "fa16.csv")
```

```{r}
fa.result6 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result6$loadings, "fa17.csv")
```

```{r}
fa.result7 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`,-`Q.11-m3`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result7$loadings, "fa18.csv")
```

```{r}
fa.result8 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`,-`Q.11-m3`,-`Q.11-m2`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result8$loadings, "fa19.csv")
```

```{r}
fa.result9 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`,-`Q.11-m3`,-`Q.11-m2`,-`Q.8-m5`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result9$loadings, "fa110.csv")
```

```{r}
fa.result10 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`,-`Q.11-m3`,-`Q.11-m2`,-`Q.8-m5`,-`Q.8-m4`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result10$loadings, "fa111.csv")
```

```{r}
fa.result11 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`,-`Q.11-m3`,-`Q.11-m2`,-`Q.8-m5`,-`Q.8-m4`,-`Q.11-m1`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result11$loadings, "fa112.csv")
```

```{r}
fa.result12 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`,-`Q.11-m3`,-`Q.11-m2`,-`Q.8-m5`,-`Q.8-m4`,-`Q.11-m1`,-`Q.8-m3`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result12$loadings, "fa113.csv")
```

```{r}
fa.result13 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`,-`Q.11-m3`,-`Q.11-m2`,-`Q.8-m5`,-`Q.8-m4`,-`Q.11-m1`,-`Q.8-m3`,-`Q.8-m2`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result13$loadings, "fa114.csv")
```

```{r}
fa.result14 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`,-`Q.11-m3`,-`Q.11-m2`,-`Q.8-m5`,-`Q.8-m4`,-`Q.11-m1`,-`Q.8-m3`,-`Q.8-m2`,-`Q.10-m10`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result14$loadings, "fa115.csv")
```

```{r}
fa.result15 = fa(select(Data,(15:87),-`Q.5-m8`,-`Q.9-m10`,-`Q.10-m9`,-`Q.10-m4`,-`Q.8-m6`,-`Q.11-m4`,-`Q.11-m3`,-`Q.11-m2`,-`Q.8-m5`,-`Q.8-m4`,-`Q.11-m1`,-`Q.8-m3`,-`Q.8-m2`,-`Q.10-m10`,-`Q.9-m4`),nfactors=8,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result15$loadings, "fa116.csv")
```

ファン行動

```{r}
corx2 = cor(select(Data,(99:118)))
eigen(corx2)$values

```

```{r}
fa.result21 = fa(select(Data,(99:118)),nfactors=5,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result21$loadings, "fa201.csv")

```

```{r}
fa.result22 = fa(select(Data,(99:118),-`Q.14-m6`),nfactors=5,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result22$loadings, "fa202.csv")

```

```{r}
fa.result23 = fa(select(Data,(99:118),-`Q.14-m6`,-`Q.15-m1`),nfactors=5,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result23$loadings, "fa203.csv")

```

```{r}
fa.result24 = fa(select(Data,(99:118),-`Q.14-m6`,-`Q.15-m1`,-`Q.14-m5`),nfactors=5,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result24$loadings, "fa204.csv")

```

```{r}
fa.result25 = fa(select(Data,(99:118),-`Q.14-m6`,-`Q.15-m1`,-`Q.14-m5`,-`Q.15-m2`),nfactors=5,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result25$loadings, "fa205.csv")
```

```{r}
fa.result26 = fa(select(Data,(99:118),-`Q.14-m6`,-`Q.15-m1`,-`Q.14-m5`,-`Q.15-m2`,-`Q.14-m9`),nfactors=5,fm="ml",rotate="promax",scores=TRUE)
write.csv(fa.result26$loadings, "fa206.csv")
```


クロンバックα

```{r}
#ファン心理
alpha1 = select(Data,"Q.5-m1","Q.5-m2","Q.5-m3","Q.5-m4","Q.5-m5","Q.5-m6","Q.5-m7","Q.5-m9","Q.5-m10","Q.6-m1","Q.6-m2","Q.6-m3") %>% alpha()
alpha1$total

alpha2 = select(Data,"Q.6-m4","Q.6-m5","Q.6-m6","Q.6-m7","Q.6-m8","Q.6-m9","Q.6-m10","Q.7-m1","Q.7-m2","Q.7-m3","Q.7-m4","Q.7-m5","Q.7-m6") %>% alpha()
alpha2$total

alpha3 = select(Data,"Q.8-m7","Q.8-m8","Q.8-m9","Q.8-m10","Q.9-m1","Q.9-m2","Q.9-m3") %>% alpha()
alpha3$total

alpha4 = select(Data,"Q.11-m5","Q.11-m6","Q.11-m7","Q.11-m8","Q.11-m9","Q.11-m10","Q.8-m1") %>% alpha()
alpha4$total

alpha5 = select(Data,"Q.9-m5","Q.9-m6","Q.9-m7","Q.9-m8","Q.9-m9","Q.10-m1","Q.10-m2","Q.10-m3") %>% alpha()
alpha5$total


alpha6 = select(Data,"Q.7-m7","Q.7-m8","Q.7-m9","Q.7-m10") %>% alpha()
alpha6$total

alpha7 = select(Data,"Q.12-m1","Q.12-m2","Q.12-m3") %>% alpha()
alpha7$total

alpha8 = select(Data,"Q.10-m5","Q.10-m6","Q.10-m7","Q.10-m8") %>% alpha()
alpha8$total


```
```{r}
#ファン行動
alpha9 = select(Data,"Q.14-m4","Q.14-m7","Q.14-m10") %>% alpha()
alpha9$total

alpha10 = select(Data,"Q.14-m1","Q.14-m2","Q.14-m3") %>% alpha()
alpha10$total

alpha11 = select(Data,"Q.14-m8","Q.15-m7","Q.15-m8") %>% alpha()
alpha11$total

alpha12 = select(Data,"Q.15-m3","Q.15-m4","Q.15-m5","Q.15-m6") %>% alpha()
alpha12$total

alpha13 = select(Data,"Q.15-m9","Q.15-m10") %>% alpha()
alpha13$total


```

構造方程式モデリング（全体）


列名の変更
```{r}
colnames(Data) = str_replace(colnames(Data_t), '-', '')
colnames(Data) = str_replace(colnames(Data_t), '\\.', '')

```



モデル
```{r}
model1 = '

#顧客期待
a1 =~ Q16m1 + Q16m2 + Q16m3 
#知覚価値
a2 =~ Q16m4 + Q16m5 + Q16m6 + Q17m1
#知覚価値
a3 =~ Q17m2 + Q17m3
#顧客満足
a4 =~ Q17m4 + Q17m5 + Q17m6

#応援ロイヤリティ
r1 =~ Q13m4 + Q13m5

#ロイヤリティ
r2 =~ r21 + r22 + r23

#一体感
r21 =~ Q12m4 + Q12m5 + Q12m6
#愛着
r22 =~ Q12m7 + Q12m8 + Q12m9
#誇り
r23 =~ Q12m10 + Q13m1 + Q13m2

#ファン行動
f1 =~ Q14m4 + Q14m7 + Q14m10
f2 =~ Q14m1 + Q14m2 + Q14m3
f3 =~ Q14m8 + Q15m7 + Q15m8
f4 =~ Q15m3 + Q15m4 + Q15m5 + Q15m6
f5 =~ Q15m9 + Q15m10

#回帰
a3 ~ a1
a2 ~ a3 + a1
a4 ~ a1 + a2 + a3

r1 ~ a4
r2 ~ a4

f1 ~ r1 + r2
f2 ~ r1 + r2
f3 ~ r1 + r2
f4 ~ r1 + r2
f5 ~ r1 + r2

'

```



```{r}
fit1 = sem(model = model1, data = Data)

summary(fit1)
```
```{r}
fitMeasures(fit1)
```

```{r}
modindices(fit1)
parameterestimates(fit1)
```

